### ISSUE TITLE
在run npm install的时候寄了

### ISSUE THREAD

**Issue by yufenyouluo** [eryajf/vdoing-template#13]
![屏幕截图 2024-03-30 202952](https://github.com/eryajf/vdoing-template/assets/74883123/3f0fc146-00d7-4ba0-ae6b-0ddb7ba54de1)

**Comment by yufenyouluo** [comment]
这是咋回事，想不通怎么会在这里寄，[捂脸]。。。

**Comment by eryajf** [comment]
额，多少给个地址，或者有错误信息也好，这让我从何看起😂

**Comment by yufenyouluo** [comment]
https://github.com/yufenyouluo/blog/actions/runs/8490695820/job/23262035804

**Comment by yufenyouluo** [comment]
![屏幕截图 2024-03-30 220955](https://github.com/eryajf/vdoing-template/assets/74883123/014ebcae-f287-4eee-98b7-9268f434eb58)
