### ISSUE TITLE
为啥一直弹窗git授权，这样很不友好

### ISSUE THREAD

**Issue by ceshi20160607** [eryajf/vdoing-template#6]
为啥一直弹窗git授权，这样很不友好

**Comment by eryajf** [comment]
默认开启了vssue的评论插件，所以打开文章的时候，会让你初始化一下，其实首次初始化完成之后，以后就不会弹了。

当然，如果你不需要这个功能，可以将 https://github.com/eryajf/vdoing-template#%E9%85%8D%E7%BD%AE%E8%AF%84%E8%AE%BA 这个地方的配置信息注释掉，就不会出现这个弹窗了！
