### ISSUE TITLE
请问，可以绑定域名吗

### ISSUE THREAD

**Issue by zhongyuanqi** [eryajf/vdoing-template#7]
如果可以的话，能出个教程吗，感谢~

**Comment by eryajf** [comment]
OK，我等会儿把这个内容补充一下，其实只需要一个很简单的配置项

**Comment by eryajf** [comment]
可参考这里的说明： [https://eryajf.github.io/HowToStartOpenSource/pages/06d15f/](https://eryajf.github.io/HowToStartOpenSource/pages/06d15f/)
